IO.read(:eof)
|> String.trim()
|> String.graphemes()
|> Enum.chunk_every(14, 1)
|> Enum.with_index()
|> Enum.find(fn {bytes, _i} -> bytes |> Enum.uniq() |> length() == length(bytes) end)
|> elem(1)
|> Kernel.+(14)
|> IO.inspect()
